# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "flowbite", to: "https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.turbo.min.js"
pin "flowbite-datepicker", to: "https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.turbo.min.js"
pin "@rails/actioncable", to: "https://ga.jspm.io/npm:@rails/actioncable@7.1.1/app/assets/javascripts/action_cable.esm.js"

# Pin ApexCharts to the local node_modules path so importmap can load it from the installed package
# During development the server may serve /node_modules; this avoids using a CDN.
pin "apexcharts", to: "vendors/apexcharts.esm.js"

# Pin custom JavaScript modules with explicit mappings
pin "modules/donor_modal", to: "modules/donor_modal.js"
pin "modules/qr_scanner", to: "modules/qr_scanner.js"
pin "modules/ticket_utils", to: "modules/ticket_utils.js"
pin "modules/zakat_calculator", to: "modules/zakat_calculator.js"
pin "modules/guests", to: "modules/guests.js"
pin "modules/healthcare_donations", to: "modules/healthcare_donations.js"
pin "modules/healthcare_manual_user_search", to: "modules/healthcare_manual_user_search.js"
pin "modules/volunteer_user_search", to: "modules/volunteer_user_search.js"
pin "modules/volunteer_form_toggle", to: "modules/volunteer_form_toggle.js"
pin "modules/mobile_navigation", to: "modules/mobile_navigation.js"
pin "modules/donor_info_modal", to: "modules/donor_info_modal.js"
pin "modules/tickets", to: "modules/tickets.js"
pin "modules/ticket_show", to: "modules/ticket_show.js"
pin "modules/event_ticket_types", to: "modules/event_ticket_types.js"
pin "modules/spot_registration_ticket_types", to: "modules/spot_registration_ticket_types.js"
pin "modules/bulk_ticket_modal", to: "modules/bulk_ticket_modal.js"
pin "modules/bulk_ticket_modal_fallback", to: "modules/bulk_ticket_modal_fallback.js"
pin "modules/carousel", to: "modules/carousel.js"
pin "modules/stats", to: "modules/stats.js"
pin "modules/gallery_tabs", to: "modules/gallery_tabs.js"
pin "modules/user_card_dropdown", to: "modules/user_card_dropdown.js"
pin "modules/project_donation", to: "modules/project_donation.js"
pin "modules/tabs_and_donors", to: "modules/tabs_and_donors.js"
pin "modules/reports_charts", to: "modules/reports_charts.js"
